### ISSUE TITLE
How to do step 2 of the `Usage` section?

### ISSUE THREAD

**Issue by xanderjakeq** [Pravica-Inc/react-native-blockstack-radiks-boilerplate#4]
I'm a beginner with mobile development and react native. So I don't know how to create a redirect page... or what that means.

**Comment by uonuon** [comment]
@xanderjakeq No, it's alright.
by mentioning this step it means when the user starts using the Blockstack SDK, and Authenticate successfully. you'll your authentication token into your redirect page which is on step 1 config `redirectUrl`, so when you authenticate successfully and you get your token, you will need to retrieve that token a browser. so that script takes your `authResponse` and redirects it to your app using deeplinking.

**Comment by xanderjakeq** [comment]
What should be the content of the redirect.html (what should it look like)? 

I am assuming the script your are talking about is the one right under step 2. Where can I find my appId?

**Comment by uonuon** [comment]
@xanderjakeq I am sorry for replying late, yes its the script written under step two.

The appId  is your `bundle Identifier`  for iOS  you can find it in infro.plist `Bundle identifier`.
or android `applicationId` at android/app/build.gradle.
